// code-snippet/chart-sdk/angular/3d-charts/tooltip/tooltip-cs7/src/app.component.ts
import { Component } from '@angular/core';
import { Chart3DAllModule } from '@syncfusion/ej2-angular-charts';
import { Chart3DTooltipRenderEventArgs } from '@syncfusion/ej2-charts';

interface SalesData {
    x: string;
    y: number;
    region: string;
    growth: number;
}

@Component({
    imports: [Chart3DAllModule],
    standalone: true,
    selector: 'app-container',
    template: `
        <ejs-chart3d id="chart3d" align="center" [primaryXAxis]="primaryXAxis" [primaryYAxis]="primaryYAxis" [tooltip]="tooltip" [rotation]="rotation" [tilt]="tilt" [depth]="depth"
            [enableRotation]="enableRotation" [wallColor]="wallColor" [title]="title" (tooltipRender)="tooltipRender($event)">
            <e-chart3d-series-collection>
                <e-chart3d-series [dataSource]="chartData" xName="x" yName="y" type="Column" name="Sales">
                </e-chart3d-series>
            </e-chart3d-series-collection>
        </ejs-chart3d>
    `
})
export class AppComponent {

    public chartData: SalesData[] = [
        { x: 'USA', y: 35, region: 'North America', growth: 12.5 },
        { x: 'UK', y: 22, region: 'Europe', growth: 9.8 },
        { x: 'India', y: 28, region: 'Asia', growth: 15.2 },
        { x: 'Germany', y: 15, region: 'Europe', growth: 7.6 }
    ];

    public primaryXAxis: Object = {
        valueType: 'Category',
        title: 'Country'
    };

    public primaryYAxis: Object = {
        title: 'Sales'
    };

    public tooltip: Object = {
        enable: true
    };

    public tooltipRender(args: Chart3DTooltipRenderEventArgs): void {
        const rawData: SalesData = args.data.rawData as SalesData;

        if (rawData) {
            args.text =
                'Sales: <b>' + rawData.y + '</b><br/>' +
                'Region: <b>' + rawData.region + '</b><br/>' +
                'Growth: <b>' + rawData.growth + '%</b>';
        }
    }

    public rotation: number = 7;
    public tilt: number = 10;
    public depth: number = 100;
    public enableRotation: boolean = true;
    public wallColor: string = 'transparent';
    public title: string = 'Sales by Country';
}

// code-snippet/chart-sdk/vue/3d-charts/user-interaction/tooltip-raw-data/app.vue
<template>
  <div id="app">
    <ejs-chart3d id="container" :primaryXAxis="primaryXAxis" :primaryYAxis="primaryYAxis" :tooltip="tooltip" :tooltipRender="tooltipRender" :wallColor="wallColor" :enableRotation="enableRotation" :rotation="rotation" :tilt="tilt" :depth="depth" :title="title">
      <e-chart3d-series-collection>
        <e-chart3d-series :dataSource="chartData" type="Column" xName="x" yName="y" name="Sales"></e-chart3d-series>
      </e-chart3d-series-collection>
    </ejs-chart3d>
  </div>
</template>
<script>
import { Chart3DComponent, Chart3DSeriesCollectionDirective, Chart3DSeriesDirective, ColumnSeries3D, Category3D, Tooltip3D } from '@syncfusion/ej2-vue-charts';

export default {
  name: 'App',
  components: {
    'ejs-chart3d': Chart3DComponent,
    'e-chart3d-series-collection': Chart3DSeriesCollectionDirective,
    'e-chart3d-series': Chart3DSeriesDirective
  },
  data() {
    return {
      chartData: [
        { x: 'USA', y: 35, region: 'North America', growth: 12.5 },
        { x: 'UK', y: 22, region: 'Europe', growth: 9.8 },
        { x: 'India', y: 28, region: 'Asia', growth: 15.2 },
        { x: 'Germany', y: 15, region: 'Europe', growth: 7.6 }
      ],
      primaryXAxis: { valueType: 'Category', title: 'Country' },
      primaryYAxis: { title: 'Sales' },
      tooltip: { enable: true },
      wallColor: 'transparent',
      enableRotation: true,
      rotation: 7,
      tilt: 10,
      depth: 100,
      title: 'Sales by Country'
    };
  },
  methods: {
    tooltipRender(args) {
      const rawData = args.data.rawData;
      if (rawData) {
        args.text = 'Sales: <b>' + rawData.y + '</b><br/>' +
          'Region: <b>' + rawData.region + '</b><br/>' +
          'Growth: <b>' + rawData.growth + '%</b>';
      }
    }
  },
  provide: {
    chart3d: [ColumnSeries3D, Category3D, Tooltip3D]
  }
};
</script>
<style>
#container {
  height: 350px;
}
</style>
